version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd frontend
      - npm install
  build:
    commands:
      - echo Building the project...
      - npm run build
  post_build:
    commands:
      - echo Executing post-build steps...
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist
  name: techcourse-project-2024/develup/frontend-deploy
