services:
  nginx:
    image: nginx
    depends_on:
      - application
    networks:
      - nginx-app-net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/custom.conf:/etc/nginx/conf.d/custom.conf
      - /etc/letsencrypt/live/dev.api.devel-up.co.kr/fullchain.pem:/etc/letsencrypt/live/dev.api.devel-up.co.kr/fullchain.pem
      - /etc/letsencrypt/live/dev.api.devel-up.co.kr/privkey.pem:/etc/letsencrypt/live/dev.api.devel-up.co.kr/privkey.pem

  application:
    image: ${BACKEND_APP_IMAGE_NAME}
    networks:
      - nginx-app-net
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Seoul"
      SPRING_PROFILE: dev
    restart: always
    container_name: develup-app

networks:
  nginx-app-net:
