services:
  nginx:
    image: nginx
    depends_on:
      - application
    networks:
      - nginx-app-net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/custom.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/api.devel-up.co.kr/fullchain.pem:/etc/letsencrypt/live/api.devel-up.co.kr/fullchain.pem
      - /etc/letsencrypt/live/api.devel-up.co.kr/privkey.pem:/etc/letsencrypt/live/api.devel-up.co.kr/privkey.pem
      - /var/log/nginx:/var/log/nginx
    container_name: nginx

  application:
    image: ${BACKEND_APP_IMAGE_NAME}
    networks:
      - nginx-app-net
    ports:
      - "8080:8080"
      - "8082:8082"
    environment:
      TZ: "Asia/Seoul"
      SPRING_PROFILE: dev
    volumes:
      - /var/log/app/logs:/var/log/app/logs
    restart: always
    container_name: develup-app

  promtail-nginx:
    image: grafana/promtail:3.0.0
    volumes:
      - /home/ubuntu/promtail/nginx-config.yml:/mnt/config/config.yml
      - /var/log/nginx:/var/log
    command:
      - config.file=/mnt/config/config.yml
    restart: unless-stopped

  promtail-app:
    image: grafana/promtail:3.0.0
    volumes:
      - /home/ubuntu/promtail/app-config.yml:/mnt/config/config.yml
      - /var/log/app/logs:/var/log
    command:
      - config.file=/mnt/config/config.yml
    restart: unless-stopped

networks:
  nginx-app-net:
