services:
  nginx:
    image: nginx
    depends_on:
      - application
    networks:
      - nginx-app-net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/custom.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/dev.api.devel-up.co.kr/fullchain.pem:/etc/letsencrypt/live/dev.api.devel-up.co.kr/fullchain.pem
      - /etc/letsencrypt/live/dev.api.devel-up.co.kr/privkey.pem:/etc/letsencrypt/live/dev.api.devel-up.co.kr/privkey.pem

  application:
    image: ${BACKEND_APP_IMAGE_NAME}
    depends_on:
      - mysql
    networks:
      - nginx-app-net
      - app-mysql-net
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Seoul"
      SPRING_PROFILE: dev
    restart: always
    container_name: develup-app

  mysql:
    image: mysql
    networks:
      - app-mysql-net
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    container_name: develup-db-dev

networks:
  nginx-app-net:
  app-mysql-net:
