SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE pair;
ALTER TABLE pair ALTER COLUMN id RESTART;
TRUNCATE TABLE submission;
ALTER TABLE submission ALTER COLUMN id RESTART;
TRUNCATE TABLE mission;
ALTER TABLE mission ALTER COLUMN id RESTART;
TRUNCATE TABLE member;
ALTER TABLE member ALTER COLUMN id RESTART;
SET REFERENTIAL_INTEGRITY TRUE;

INSERT INTO member (id)
VALUES (1);

INSERT INTO member (id)
VALUES (2);
