export const ROUTES = {
  main: '/',
  missionDetail: '/missions',
  missionList: '/missions',
  profile: '/profile',
  guide: '/guide',
  submitSolution: '/submit/solution',
  error: '/error',
  solutions: '/solutions',
  dashboardHome: '/dashboard',
  dashboardMissionInProgress: 'in-progress-mission',
  dashboardSubmittedSolution: 'submitted-solution',
  dashboardComments: 'comments',
  about: '/about',
  discussions: '/discussions',
} as const;
