api-host: http://localhost:8080
client-host: http://localhost:3000

auth:
  github:
    client-id: develup-test-develup-test-develup-test-develup-test-develup-test
    client-secret: develup-test-develup-test-develup-test-develup-test-develup-test
    redirect-uri: ${api-host}/auth/social/callback/github
    client-uri: ${client-host}
