name: "Chromatic"

on:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20.15.1
      - name: Install dependencies
        run: |
          if [ ! -f package-lock.json ]; then
            npm install
          fi
          npm ci
        working-directory: ./frontend
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        working-directory: ./frontend
