name: Notify FE

on:
  workflow_run:
    workflows: ["CI FE"]
    types:
      - completed

jobs:
  FE_SLACK_MESSAGE:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get teamMember List
        id: teamMembers
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const workers = JSON.parse(fs.readFileSync('.github/workflows/teamMember.json'));
            const mention = context.payload.pull_request.assignees.map((user) => {
            const login = user.login;
            const mappedValue = workers[login];
            return mappedValue ? `<@${mappedValue}>` : `No mapping found for ${login}`;
            })
            return mention.join(', ');

      - name: Call notify workflow
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.ISSUE_CHANNEL }}
          payload: |
            {
                "text": "pr 테스트 결과",
                "blocks": [
                  {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "pr 테스트 결과\n lint : ${{ github.event.workflow_run.outputs.lint }} \n build : ${{ github.event.workflow_run.outputs.build }} \n test : ${{ github.event.workflow_run.outputs.test }} \n • 링크: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}> \n • pr 담당자: \${{ steps.teamMembers.outputs.result }}
                      }
                  }
                ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
